services:
  - type: web
    name: real-estate-backend
    env: node
    buildCommand: npm run render-build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    # Health check endpoint
    healthCheckPath: /status